<div dir="ltr" style="text-align: left;" trbidi="on">
  <script>
    <?= $block->getElementId() ?> = {
      activationCodeWindow: undefined,
      openActivationCodeWindow(e) {
        e.preventDefault()
        
        <?= $block->getElementId() ?>.activationCodeWindow = window.open('<?= $block->getEndpoint() ?>/ecommerce-authentication/?public_key=<?= $block->getPublicKey() ?>&type=magento', 'satispay_ActivationCodeWindow')

        window.removeEventListener('message', <?= $block->getElementId() ?>.activationCodeWindowMessage)
        window.addEventListener('message', <?= $block->getElementId() ?>.activationCodeWindowMessage, false)
      },
      activationCodeWindowMessage(e) {
        console.log(e)
        
        if (e.source !== <?= $block->getElementId() ?>.activationCodeWindow) {
          return
        }

        if (e.data.action === 'done') {
          e.source.close()
          window.removeEventListener('message', <?= $block->getElementId() ?>.activationCodeWindowMessage)

          var inputElement = document.getElementsByName('groups[satispay][fields][<?= $block->getKeyIdFieldName() ?>][value]')[0]
          inputElement.value = e.data.payload.keyID
          inputElement.form.submit()
        }
      }
    }
  </script>
  <a class="button action-default" href="#" onclick="<?= $block->getElementId() ?>.openActivationCodeWindow(event)"><?= $block->escapeHtml($block->getButtonLabel()) ?></a>
</div>
